-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

jA0ECQMCVf+HcqXE6Mxg0nYBXUjTVQ7C+S6365xNeVuFFnMCTGS5IwGr0ButQZHJ
FsU1XNk1SWtAobdq/PGAdhcWrTVg/RLN+ZWdcpke5xc2EFKpHat5OYdc8zl3XNBo
BT/NtKTqp7trV1vaNWNltzJC0XSlAV1GML1i0k3vO8vqDxPHYc+l
=bbYX
-----END PGP MESSAGE-----
