#!/bin/bash

ROOT='..'
HOME="$ROOT/home"
SKEL="$ROOT/etc/skel"

source "$ROOT/lib/sh/common.sh"

PASSWD=`cat $ROOT/etc/passwd.json | json -b`

for ((l=`last "$PASSWD"`, i=0; i<=l; i++)); do
	SVC=$(bool `field $i service`)

	echo \
	useradd --no-user-group	\
					--base-dir 					"$HOME" \
					--skel 							"$SKEL" \
					--uid 							"`field "$PASSWD" $i uid`" \
					--shell 						"`field "$PASSWD" $i shell`" \
					--password 					"`field "$PASSWD" $i password`" \
					--comment 					"{ \"uri\": \"`field "$PASSWD" $i uri`\", \"info\": \"`field "$PASSWD" $i info`\", \"service\": ${SVC:-false} }" \
					${SVC:+--system} \
					`field "$PASSWD" $i username`
done
