#!/bin/bash

source "$SERVER_ROOT/lib/bash/common.bash"

GROUP=`cat $SERVER_ROOT/etc/group.json | json -b`

for ((l=`last "$GROUP"`, i=0; i<=l; i++)); do
	groupadd --gid "`field "$GROUP" $i gid`" `field "$GROUP" $i group`
done

exit 0
