#!/bin/bash

source "$SERVER_ROOT/lib/bash/common.bash"

HOME="$SERVER_ROOT/home"
SKEL="$SERVER_ROOT/etc/skel"
PASSWD=`cat $SERVER_ROOT/etc/passwd.json | json -b`

for ((l=`last "$PASSWD"`, i=0; i<=l; i++)); do
  SVC=$(bool `field $i service`)
  COMMENT=$(echo "{ \"uri\": `nullstring $(field "$PASSWD" $i uri)`, \"info\": \"`field "$PASSWD" $i info`\", \"service\": ${SVC:-false} }" | base64 -w 0)
  NAME="`field "$PASSWD" $i username`"
  useradd --no-user-group \
          --create-home \
          --home-dir          "$HOME/$NAME" \
          --skel              "$SKEL" \
          --uid               "`field "$PASSWD" $i uid`" \
          --gid               "`field "$PASSWD" $i gid`" \
          --shell             "`field "$PASSWD" $i shell`" \
          --password          "`field "$PASSWD" $i password`" \
          --comment           "$COMMENT" \
          ${SVC:+--system} \
          $NAME

  chown -R "$NAME:$NAME" "$HOME/$NAME"
  chmod -R u+rw,g+r,o+r "$HOME/$NAME" 
done

exit 0
