#!/bin/bash

source "$ROOT/lib/sh/common.sh"

GROUP=`cat $ROOT/etc/group.json | json -b`

for ((l=`last "$GROUP"`, i=0; i<=l; i++)); do
	groupadd --gid "`field "$GROUP" $i gid`" `field "$GROUP" $i group`
done
