#!/bin/bash

source "$SERVER_ROOT/lib/bash/common.bash"

if [ -z "$SERVER_SECRET" ]; then
  echo "Server secret missing from environment."
  exit 1
fi

if [ -n "$SERVER_SECRET_ROTATE" -a \( "$SERVER_SECRET" != "$SERVER_SECRET_ROTATE" \) ]; then
  echo "Rotate: decrypt using old key, encrypt using new key."
  SERVER_SECRET="$SERVER_SECRET_ROTATE"
fi

for FILE in `private "$SERVER_ROOT"`; do
  if file "$FILE" | grep -ivq 'PGP'; then
    continue
  fi

  TMP=`mktemp /tmp/server.XXXXXX`

  if gpg -ad --cipher-algo AES256 --passphrase "$SERVER_SECRET" > "$TMP" < "$FILE"; then
    # this should preserve file permissions (mv would not)
    cat "$TMP" > "$FILE"
  fi
  
  rm "$TMP"
done

exit 0
