#!/bin/bash

source "$ROOT/lib/sh/common.sh"

if [ -z "$SERVER_SECRET" ]; then
  echo "Server secret missing from environment."
  exit 1
fi

for FILE in `private "$ROOT"`; do
  if file "$FILE" | grep -iq 'PGP'; then
    continue
  fi

  TMP=$(mktemp -t server)

  if gpg -ac --cipher-algo AES256 --passphrase "$SERVER_SECRET" > "$TMP" < "$FILE"; then
    mv "$TMP" "$FILE"
  else
    rm "$TMP"
  fi
done

exit 0
