#!/bin/bash

if [ \! -d "$ROOT" ]; then
  echo "The root environment variable must be set to valid directory"
  exit 1
fi

source "$ROOT/lib/sh/common.sh"

SECRET="$ROOT/etc/key.secret"

INIT=`cat $ROOT/etc/init.json | json -b`
if (( $? )); then
  echo "FAIL: init.json is not valid JSON!"
  exit 2
fi

PASSWD=`cat $ROOT/etc/passwd.json | json -b`
if (( $? )); then
  echo "FAIL: passwd.json is not valid JSON!"
  exit 3
fi

GROUP=`cat $ROOT/etc/group.json | json -b`
if (( $? )); then
  echo "FAIL: group.json is not valid JSON!"
  exit 4
fi

GROUP=`cat $ROOT/etc/crontab.json | json -b`
if (( $? )); then
  echo "FAIL: crontab.json is not valid JSON!"
  exit 5
fi

validate_init() {
  true
}

validate_passwd() {
  true
}

validate_group() {
  # TODO Validate that every user has their own group
  true
}

validate_key() {
  if [ ! -r "$SECRET" ]; then
    echo "FAIL: secret key not found!"
    exit 6
  fi
}

validate_init
validate_group
validate_passwd
validate_key
