#!/bin/bash

if [ \! -d "$SERVER_ROOT" ]; then
  echo "The root environment variable must be set to valid directory"
  exit 1
fi

source "$SERVER_ROOT/lib/bash/common.bash"

service rsyslog start
service cron start

exit 0
