#!/bin/bash

source "$SERVER_ROOT/lib/sh/common.sh"

ACL="$SERVER_ROOT/etc/permissions.acl"

# This excludes *any* files containing the blacklisted paths anywhere in its path
find "$SERVER_ROOT" -not \( -path '*node_modules*' -o -path '*.git*' \) -print0  | xargs -0 getfacl -p > "$ACL"

exit 0
