#!/bin/bash

source "$SERVER_ROOT/lib/sh/common.sh"

HOME="$SERVER_ROOT/home"
DEST="$SERVER_ROOT/etc/group.json"
TMP=`mktemp /tmp/server.XXXXXX`

cat /etc/group | while read LINE; do
  if echo "$LINE" | grep -q '^ *#'; then
    continue
  fi

  echo -e \
    "{" \
    "\"group\": \"`echo "$LINE" | cut -d: -f1`\"," \
    "\"gid\": \"`echo "$LINE" | cut -d: -f3`\"," \
    "\"users\": [`echo "$LINE" | cut -d: -f4 | sed -e 's/ *, */", "/g' -e 's/^/"/' -e 's/\$/"/' | sed -e 's/""//' `]" \
    "},"
done > "$TMP"

echo -e "[\n`noblank "$(nocomma "$(cat "$TMP")")"`\n]" > "$DEST"
rm "$TMP"

exit 0
