#!/bin/bash

source "$SERVER_ROOT/lib/bash/common.bash"

CRON=`cat $SERVER_ROOT/etc/crontab.json | json -b`
CRONTAB=""

for ((l=`last "$CRON"`, i=0; i<=l; i++)); do
  CRONTAB="$CRONTAB\n$(field "$CRON" $i pattern) $(field "$CRON" $i command)"
done

noblank "$CRONTAB" | crontab

exit 0
