#!/bin/bash

source "$SERVER_ROOT/usr/lib/bash/cgi/getvar.bash"
source "$SERVER_ROOT/usr/lib/bash/json/escape.bash"

cgi_getvars GET path

MAP="{}"
STATUS=500

if [ -d "$path" -a -x "$path" ]; then
  MAP="::"
  DATA="["

  for ITEM in `ls -aLFR "$path" 2> /dev/null | sed -e 's/\*$/!/'`; do
    if echo "$ITEM" | grep -q ':$'; then
        DATA=$(echo "$DATA" | sed -e 's/,\?$/ ]/')
        MAP="$MAP $DATA, `json_escape "${ITEM::${#ITEM}-1}"`:"
        DATA="["
        continue
    fi 
    
    TYPE="-"
    
    if echo "$ITEM" | grep -q '[\/\*@=%\|!]$'; then
      TYPE="${ITEM:${#ITEM}-1}"
      ITEM="${ITEM::${#ITEM}-1}"
    fi
    
    DATA="$DATA { \"path\": `json_escape "$ITEM"`, \"type\": \"${TYPE/!/*}\" },"
  done
  
  DATA=$(echo "$DATA" | sed -e 's/,\?$/ ]/')
  MAP=$(echo "{ $MAP $DATA }" | sed -e 's/^{\s*::[^,}]*,\?\(}\?\)/{ \1/')
  STATUS=200
fi

echo "Content-type: application/json"
echo "Status: $STATUS"
echo ""
echo "$MAP"
